# Generated by Django 4.1.4 on 2023-01-01 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dialogic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="magic_link",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="student",
            name="magic_link",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="studentsession",
            name="magic_link",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="teacher",
            name="auth",
            field=models.CharField(blank=True, default=str, max_length=200),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="magic_link",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
