# Generated by Django 4.1.4 on 2023-01-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dialogic", "0002_session_magic_link_student_magic_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="description",
        ),
    ]
