# Generated by Django 4.1.4 on 2023-01-01 19:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogic", "0003_remove_session_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="duration_milliseconds",
            new_name="end_time",
        ),
        migrations.AddField(
            model_name="session",
            name="start_time",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="session",
            name="graph",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="student_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), blank=True, size=None
            ),
        ),
    ]
