# Generated by Django 4.1.4 on 2023-01-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogic", "0004_rename_duration_milliseconds_session_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="annotations",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="discussion_state",
            field=models.CharField(default="initial", max_length=200),
        ),
    ]
